Starts the VM but then
I an't login most likely because of

running activation script...
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "\x{0}\x{0}\x{0}\x{0}...") at /nix/store/1hkp2n6hz3ybf2rvkjkwrzgbjkrrakzl-update-users-groups.pl line 11.
Activation script snippet 'users' failed (2)
setting up /etc...
removing obsolete file ‘/etc/’...
chown: invalid user: 'root:root'
Activation script snippet 'var' failed (1)
chown: invalid user: 'root.messagebus'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.root'
chown: invalid user: 'root.nogroup'
Activation script snippet 'wrappers' failed (1)
warning: the group 'nixbld' specified in 'build-users-group' does not exist
error: '/nix/var/nix/db/schema' is corrupt
starting systemd...

The bad json is supposed to be in "/var/lib/nixos/uid-map" ?